### ISSUE TITLE
Using this outside of `bot.help_command`

### ISSUE THREAD

**Issue by CircuitSacul** [stroupbslayen/discord-pretty-help#19]
If I wanted `help` to be a custom command, but also wanted to use this as `commands`, is this possible? (Also if you give me your discord, it might be easier to discuss it there)

**Comment by stroupbslayen** [comment]
Yea, that's possible. The discord.py `HelpCommand` has a [command_attrs](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=helpcommand#discord.ext.commands.HelpCommand.command_attrs) argument you can use.
`PrettyHelp( command_attrs={"name": "commands"} )` would allow you to call the command with `!commands` instead of `!help`

My discord is StroupBSlayen#3487
