### ISSUE TITLE
Prepend Command group in commands

### ISSUE THREAD

**Issue by anselal** [stroupbslayen/discord-pretty-help#66]
Hi there,

when calling help on a command group the command group is displayed first and then the all the commands in that command group.
It would be useful to prepend the command group in the commands so the user is aware what he has to call.
The way it is displayed now, if the user does not know that it is a command group, he tries to call the command without the command group and the command fails

![2021-10-27_01h08_14](https://user-images.githubusercontent.com/8732668/138968017-cae72150-8d04-4331-9df2-ecd8c37dacd1.png)

In the above example `autoroles` is a command group and the other 2 commands belong to autorole but this is not "visible".
The user has to call `autoroles set` or `autoroles get` but the way the commands are displayed the user understands that there are 3 commands: 

- autoroles
- get
- set

which is not the case

**Comment by prakarsh17** [comment]
Yes It would be helpful please reply

**Comment by stroupbslayen** [comment]
I like this and thought about adding it initially but decided to not do it due to group commands having no limit to their depth, this could lead to problems with the character limit in the embed field name. A middle ground I came up with is to add an link emoji (🔗) to the subcommands to make it a bit more clear to the user... hopefully
![image](https://user-images.githubusercontent.com/29642143/185805202-83e545a2-6327-4d64-8b00-8948f0dff0a0.png)
